server:
  port: 9001


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mvc?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
  thymeleaf:
    cache: false


mybatis:
  type-aliases-package: com.mybatistest.demo.domain
#  mapper-locations: classpath:mapper/*.xml


  #mybatis:
#  typeAliasesPackage: com.example.mybaitsxml.dao.entity
#  mapperLocations: classpath:mapper/*.xml
  #configLocation: classpath:/mybatis-config.xml

